# Generated by Django 4.1.7 on 2023-02-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('creation', models.DateTimeField(verbose_name='date creation')),
                ('cylindre', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
            ],
        ),
    ]
